import { Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, ListItemText, MenuItem, Select, Stack, TextField, Typography } from '@mui/material'
import { useState } from 'react'
import type { ActionItem, ActionPriority, Participant } from '../../types/meeting'

export type ActionInput = { description?: string; assigneeUserIds: string[]; dueAt: string | null; priority: ActionPriority }
type Props = { action: ActionItem | null; participants?: Participant[]; open: boolean; saving: boolean; includeDescription?: boolean; onClose: () => void; onSave: (input: ActionInput) => void }

export function ActionItemEditor({ action, participants = [], open, saving, includeDescription = false, onClose, onSave }: Props) {
  const [description, setDescription] = useState(action?.description ?? '')
  const [selectedAssigneeIds, setSelectedAssigneeIds] = useState<string[]>(action?.assigneeUserIds?.length ? action.assigneeUserIds : action?.assigneeUserId ? [action.assigneeUserId] : [])
  const [dueAt, setDueAt] = useState(action?.dueAt ? action.dueAt.slice(0, 10) : '')
  const [priority, setPriority] = useState<ActionPriority>(action?.priority ?? 'Medium')

  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{includeDescription ? 'Manuel aksiyon ata' : 'Aksiyon bilgilerini düzenle'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{includeDescription && <TextField label="Görev / aksiyon açıklaması" value={description} onChange={(event) => setDescription(event.target.value)} multiline minRows={2} autoFocus slotProps={{ htmlInput: { maxLength: 1000 } }} />}<FormControl fullWidth><InputLabel id="action-assignees-label">Aksiyon sorumluları</InputLabel><Select labelId="action-assignees-label" label="Aksiyon sorumluları" multiple value={selectedAssigneeIds} onChange={(event) => setSelectedAssigneeIds(typeof event.target.value === 'string' ? event.target.value.split(',') : event.target.value as string[])} renderValue={(selected) => { const ids = selected as string[]; return ids.length ? participants.filter((participant) => ids.includes(participant.userId)).map((participant) => participant.displayName).join(', ') : 'Katılımcı seçin' }}>{participants.length ? participants.map((participant) => <MenuItem key={participant.userId} value={participant.userId}><Checkbox checked={selectedAssigneeIds.includes(participant.userId)} /><ListItemText primary={participant.displayName} secondary={participant.email} /></MenuItem>) : <MenuItem disabled value="">Toplantıda katılımcı yok</MenuItem>}</Select></FormControl><Typography variant="caption" color="text.secondary">Aksiyon yalnızca bu toplantının katılımcılarına atanabilir. Birden fazla kişi seçebilirsiniz.</Typography><TextField label="Termin tarihi" type="date" value={dueAt} onChange={(event) => setDueAt(event.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><TextField select label="Öncelik" value={priority} onChange={(event) => setPriority(event.target.value as ActionPriority)}><MenuItem value="High">Yüksek</MenuItem><MenuItem value="Medium">Orta</MenuItem><MenuItem value="Low">Düşük</MenuItem></TextField></Stack></DialogContent><DialogActions><Button onClick={onClose}>İptal</Button><Button variant="contained" disabled={saving || (includeDescription && !description.trim())} onClick={() => onSave({ ...(includeDescription ? { description: description.trim() } : {}), assigneeUserIds: selectedAssigneeIds, dueAt: dueAt ? new Date(`${dueAt}T23:59:59`).toISOString() : null, priority })}>{saving ? 'Kaydediliyor…' : 'Kaydet'}</Button></DialogActions></Dialog>
}
