import { Alert, Box, Button, Card, CardContent, Chip, Grid, Stack, Typography } from '@mui/material'
import { navigate } from '../../app/navigation'
import type { Meeting } from '../../types/meeting'

const statusLabels: Record<string, string> = { '0': 'Planlandı', '1': 'Kayıt alınıyor', '2': 'İşleniyor', '3': 'Hazır', '4': 'Başarısız', '5': 'İptal', '6': 'Tamamlandı', Scheduled: 'Planlandı', Recording: 'Kayıt alınıyor', Processing: 'İşleniyor', Ready: 'Hazır', Failed: 'Başarısız', Cancelled: 'İptal', Completed: 'Tamamlandı' }
const statusColors: Record<string, 'default' | 'success' | 'warning' | 'error' | 'info'> = { '0': 'default', '1': 'warning', '2': 'info', '3': 'success', '4': 'error', '5': 'default' }
function statusOf(meeting: Meeting): string { return String(meeting.status) }

export function DashboardPage({ meetings, canCreateMeetings }: { meetings: Meeting[]; canCreateMeetings: boolean }) {
  const today = new Date().toDateString()
  const todayMeetings = meetings.filter((meeting) => new Date(meeting.startsAt).toDateString() === today)
  const completedSummaries = meetings.filter((meeting) => meeting.summary !== null).length
  const openActions = meetings.reduce((total, meeting) => total + (meeting.summary?.actionItems.filter((action) => !action.completed).length ?? 0), 0)
  return <Stack spacing={3}><Stack direction={{ xs: 'column', md: 'row' }} sx={{ justifyContent: 'space-between', gap: 2, p: 4, background: 'linear-gradient(120deg, #241640 0%, #3B246B 62%, #6D52A5 100%)', color: 'white', borderRadius: 4, position: 'relative', overflow: 'hidden', '&::after': { content: '""', position: 'absolute', width: 240, height: 240, borderRadius: '50%', right: -70, top: -110, bgcolor: 'rgba(255, 107, 107, 0.22)' } }}><Box sx={{ position: 'relative', zIndex: 1 }}><Typography variant="overline" sx={{ color: 'secondary.light', fontWeight: 800, letterSpacing: 2 }}>MEETING WORKSPACE</Typography><Typography variant="h4">Toplantılarınızı netleştirin 👋</Typography><Typography sx={{ color: 'rgba(255,255,255,0.74)' }}>{new Intl.DateTimeFormat('tr-TR', { dateStyle: 'full' }).format(new Date())} — Takvim, AI özetleri ve aksiyonlar tek yerde</Typography></Box>{canCreateMeetings && <Button variant="contained" color="secondary" onClick={() => navigate('/meetings')} sx={{ position: 'relative', zIndex: 1 }}>＋ Yeni toplantı başlat</Button>}</Stack>
    <Grid container spacing={2}>{[['Toplam Toplantı', meetings.length, 'primary.main'], ['Bugünkü Program', todayMeetings.length, 'secondary.main'], ['Tamamlanan AI Özetler', completedSummaries, 'success.main'], ['Açık Görevler / Aksiyonlar', openActions, 'warning.main']].map(([label, value, color]) => <Grid key={String(label)} size={{ xs: 12, sm: 6, md: 3 }}><Card sx={{ borderLeft: 5, borderColor: color }}><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h3" sx={{ color }}>{value}</Typography></CardContent></Card></Grid>)}</Grid>
    <Grid container spacing={3}><Grid size={{ xs: 12, md: 7 }}><Card><CardContent><Stack direction="row" sx={{ justifyContent: 'space-between', mb: 2 }}><Typography variant="h5">📅 Günlük Takvim & Toplantı Akışı</Typography><Chip label={new Intl.DateTimeFormat('tr-TR').format(new Date())} variant="outlined" /></Stack>{todayMeetings.length ? <Stack spacing={2}>{todayMeetings.map((meeting) => <Card key={meeting.id} variant="outlined" sx={{ p: 1, borderLeft: 4, borderColor: 'secondary.main' }}><Stack direction="row" sx={{ justifyContent: 'space-between', alignItems: 'center' }}><Typography sx={{ fontWeight: 700 }}>{new Date(meeting.startsAt).toLocaleTimeString('tr-TR', { hour: '2-digit', minute: '2-digit' })} {meeting.endsAt ? `- ${new Date(meeting.endsAt).toLocaleTimeString('tr-TR', { hour: '2-digit', minute: '2-digit' })}` : ''}</Typography><Button onClick={() => navigate(`/meetings/${meeting.id}`)}>İncele & Not Al →</Button></Stack><Typography variant="h6">{meeting.title}</Typography><Typography color="text.secondary">Düzenleyen: {meeting.organizerEmail ?? meeting.organizerId}</Typography><Chip size="small" label={statusLabels[statusOf(meeting)] ?? statusOf(meeting)} color={statusColors[statusOf(meeting)] ?? 'default'} /></Card>)}</Stack> : <Alert severity="info">Bugün için planlanmış toplantı yok.</Alert>}</CardContent></Card></Grid><Grid size={{ xs: 12, md: 5 }}><Card sx={{ height: '100%', borderTop: 5, borderColor: 'secondary.main' }}><CardContent><Typography variant="h5">🤖 Son AI Toplantı Özeti</Typography>{meetings.find((meeting) => meeting.summary)?.summary ? <><Typography variant="h6" sx={{ mt: 3 }}>{meetings.find((meeting) => meeting.summary)?.title}</Typography><Typography sx={{ mt: 1, p: 2, bgcolor: 'grey.100', borderRadius: 2, fontStyle: 'italic' }}>{meetings.find((meeting) => meeting.summary)?.summary?.overview}</Typography><Button fullWidth sx={{ mt: 2 }} variant="contained" onClick={() => navigate(`/meetings/${meetings.find((meeting) => meeting.summary)?.id}`)}>Toplantıyı İncele</Button></> : <Alert severity="info" sx={{ mt: 2 }}>Henüz AI özeti bulunmuyor.</Alert>}</CardContent></Card></Grid></Grid>
  </Stack>
}
