import { Button, Card, CardContent, Chip, Stack, TextField, Typography } from '@mui/material'
import { useMemo, useState } from 'react'
import { navigate } from '../../app/navigation'
import type { Meeting } from '../../types/meeting'

export function MeetingsPage({ meetings, canCreateMeetings, onCreateMeeting }: { meetings: Meeting[]; canCreateMeetings: boolean; onCreateMeeting: () => void }) {
  const [search, setSearch] = useState('')
  const filtered = useMemo(() => meetings.filter((meeting) => meeting.title.toLocaleLowerCase('tr-TR').includes(search.toLocaleLowerCase('tr-TR'))), [meetings, search])
  const statusOf = (meeting: Meeting) => String(meeting.status)
  const statusLabel = (meeting: Meeting) => ({ '0': 'Planlandı', '1': 'Kayıt alınıyor', '2': 'İşleniyor', '3': 'Hazır', '4': 'Başarısız', '5': 'İptal edildi', '6': 'Tamamlandı', Scheduled: 'Planlandı', Recording: 'Kayıt alınıyor', Processing: 'İşleniyor', Ready: 'Hazır', Failed: 'Başarısız', Cancelled: 'İptal edildi', Completed: 'Tamamlandı' } as Record<string, string>)[statusOf(meeting)] ?? statusOf(meeting)
  const statusColor = (meeting: Meeting): 'default' | 'success' | 'warning' | 'error' | 'info' => statusOf(meeting) === '6' || statusOf(meeting) === 'Completed' ? 'success' : statusOf(meeting) === '4' || statusOf(meeting) === 'Failed' ? 'error' : statusOf(meeting) === '1' || statusOf(meeting) === 'Recording' ? 'warning' : statusOf(meeting) === '2' || statusOf(meeting) === 'Processing' ? 'info' : 'default'
  return <Stack spacing={3}><Stack direction="row" sx={{ justifyContent: 'space-between', alignItems: 'center' }}><Typography variant="h3">Toplantılar</Typography>{canCreateMeetings && <Button variant="contained" onClick={onCreateMeeting}>＋ Yeni Toplantı</Button>}</Stack><Card><CardContent><TextField fullWidth placeholder="Toplantı başlığı ara..." value={search} onChange={(event) => setSearch(event.target.value)} /></CardContent></Card><Card><CardContent><Stack spacing={0}>{filtered.map((meeting) => <Stack key={meeting.id} direction={{ xs: 'column', md: 'row' }} sx={{ py: 2, gap: 2, alignItems: { md: 'center' }, borderBottom: 1, borderColor: 'divider' }}><Typography sx={{ flex: 2, fontWeight: 700 }}>{meeting.title}</Typography><Typography sx={{ flex: 1 }}>{new Date(meeting.startsAt).toLocaleDateString('tr-TR')}</Typography><Typography sx={{ flex: 1 }}>{new Date(meeting.startsAt).toLocaleTimeString('tr-TR', { hour: '2-digit', minute: '2-digit' })}</Typography><Chip label={statusLabel(meeting)} color={statusColor(meeting)} /><Button variant="outlined" onClick={() => navigate(`/meetings/${meeting.id}`)}>◉ İncele & Not Al</Button></Stack>)}{!filtered.length && <Typography color="text.secondary">Aramanızla eşleşen toplantı bulunamadı.</Typography>}</Stack></CardContent></Card></Stack>
}
